name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 📦 Install Shorebird CLI (bash)
        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
        run: ./install.sh
        shell: bash

      - name: 📦 Install Shorebird CLI (powershell)
        if: matrix.os == 'windows-latest'
        run: ./install.ps1
        shell: pwsh
